/**********************************************************/
/* Automatically generated by './mkconfig': do note edit! */
/**********************************************************/
#define PRECOSAT_CXX "g++ (Debian 4.4.5-8) 4.4.5"
#define PRECOSAT_CXXFLAGS "-O3 -m32 -static -Wall -Wextra -DNDEBUG -DNLOGPRECO -DNSTATSPRECO $(PROF)"
#define PRECOSAT_OS "Linux sleepy 2.6.32-5-amd64 x86_64"
#define PRECOSAT_COMPILED "Thu Mar 17 07:43:33 CET 2011"
#define PRECOSAT_RELEASED "Sun Aug  1 11:04:22 CEST 2010"
#define PRECOSAT_VERSION "570"
#define PRECOSAT_ID "239dbbe3c72839a68b7175ca93c9d9abdeaa36c9"
