#!/usr/bin/env python3
# Writes the table of the models compiled into the FINAL_PREDICTOR build:
# one entry per tier, the arrays themselves come from xxd-alike.py on
# src/predict/predictor_<tier>.json
# usage: embed_models.py -o pred_embedded_gen.cpp tier [tier ...]
import argparse
if __name__ == "__main__":
    p = argparse.ArgumentParser()
    p.add_argument("tiers", nargs="+")
    p.add_argument("-o", "--out", required=True)
    o = p.parse_args()
    with open(o.out, "w") as f:
        f.write("//generated by embed_models.py, do not edit\n#include \"cl_predictors_abs.h\"\n")
        for t in o.tiers:
            f.write("extern unsigned char predictor_%s_json[];\nextern unsigned int predictor_%s_json_len;\n"
                    "extern const char* predictor_%s_json_hash;\n" % (t, t, t))
        f.write("namespace CMSat {\nconst EmbeddedModel embedded_models[] = {\n")
        for t in o.tiers:
            f.write('    {"%s", predictor_%s_json, predictor_%s_json_len, predictor_%s_json_hash},\n' % (t, t, t, t))
        f.write("};\nconst unsigned embedded_models_num = %d;\n}\n" % len(o.tiers))
